### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by ShayHall** [Brew-Keeper/brew-keeper-gui#1]

**Comment by ShayHall** [comment]
### Milestone 1

* [ ] User can see Default Recipes (formulas)

* [ ] User "CRUD" their own recipes

* [ ] User Creation

* [ ] User Login

* [ ] User can navigate to external links for more info (World Champs, how to, etc)

#### Milestone 2

* [ ] User can use "Brew It" Button (time as part of recipe)

* [ ] User can rate their own recipes (and edit rating)

* [ ] User can filter/sort-by...

* [ ] User can comment on their own recipes

* [ ] Styles

**Comment by s4dmw** [comment]
##### release/0.0.0 (yak-shaving)
feature/yak-shaving:
 - setup boilerplate website, partial pages, angular controller, ng-route basics
 - PR for https://github.com/Brew-Keeper/brew-keeper-gui/pull/2

**Comment by s4dmw** [comment]
##### release/0.1.0
 - feature/recipe-list-page to develop: https://github.com/Brew-Keeper/brew-keeper-gui/pull/7

**Comment by ShayHall** [comment]
##### release/0.2.0
 - feature/wire-api to develop: https://github.com/Brew-Keeper/brew-keeper-gui/pull/17

**Comment by s4dmw** [comment]
##### not merged yet. does this need to go in the next release?
- feature/brewit-step-number-fix to develop: https://github.com/Brew-Keeper/brew-keeper-gui/pull/28
